### ISSUE TITLE
Extremely slow after 8 variables.

### ISSUE THREAD

**Issue by daveime68** [carbocation/PHP-Multivariate-Regression#2]
The regression calculation quickly becomes exponentially too long to calculate, even with what I'd consider only a moderate amount of rows.

```
list($usec, $sec) = explode(" ", microtime());
$aa = ((float)$usec + (float)$sec);

$regression = new Regression();
$regression->setX(new Matrix($predictors));
$regression->setY(new Matrix($predicted));
$regression->exec();

list($usec, $sec) = explode(" ", microtime());
$bb = ((float)$usec + (float)$sec);

echo $aa.' '.$bb.' '.($bb-$aa);
```

Where predictors / predicted contain 256 "rows", and N predictor variables.

N = 5, time = 0.084s
N = 6, time = 0.628s
N = 7, time = 7.017s
N = 8, time = 49.096s
N = 9, time = 592.167s

Essentially rendering this useless for any serious application.

**Comment by carbocation** [comment]
Yes, I cannot recommend this for scientific computing. Since I haven't used PHP in many years, I'm going to archive this repository. Thanks for taking the time to check it out.
